WITH x(eligible_commit, engine, instance_commited, instance_size, multiply) AS (
    VALUES
         -- Aurora PostgreSQL
         (TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.large',     1) -- db.r7g
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.xlarge',    2)
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.2xlarge',   4)
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.4xlarge',   8)
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.8xlarge',  16)
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.12xlarge', 24)
        ,(TRUE, 'aurora-postgresql', 'db.r7g.large', 'db.r7g.16xlarge', 32)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.large',     1) -- db.r6g
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.xlarge',    2)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.2xlarge',   4)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.4xlarge',   8)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.8xlarge',  16)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.12xlarge', 24)
        ,(TRUE, 'aurora-postgresql', 'db.r6g.large', 'db.r6g.16xlarge', 32)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.large',    1) -- db.r6i
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.xlarge',   2)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.2xlarge',  4)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.4xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.8xlarge', 16)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.12xlarge',24)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.16xlarge',32)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.24xlarge',48)
        ,(FALSE, 'aurora-postgresql', 'db.r6i.large', 'db.r6i.32xlarge',64)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.large',    1) -- db.r5b
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.xlarge',   2)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.2xlarge',  4)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.4xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.8xlarge', 16)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.12xlarge',24)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.16xlarge',32)
        ,(FALSE, 'aurora-postgresql', 'db.r5b.large', 'db.r5b.24xlarge',48)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.large',    1) -- db.r5d
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.xlarge',   2)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.2xlarge',  4)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.4xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.8xlarge', 16)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.12xlarge',24)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.16xlarge',32)
        ,(FALSE, 'aurora-postgresql', 'db.r5d.large', 'db.r5d.24xlarge',48)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.large',      1) -- db.r5
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.xlarge',     2)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.2xlarge',    4)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.4xlarge',    8)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.8xlarge',   16)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.12xlarge',  24)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.16xlarge',  32)
        ,(FALSE, 'aurora-postgresql', 'db.r5.large', 'db.r5.24xlarge',  48)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.large',      1) -- db.r4
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.xlarge',     2)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.2xlarge',    4)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.4xlarge',    8)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.8xlarge',   16)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.12xlarge',  24)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.16xlarge',  32)
        ,(FALSE, 'aurora-postgresql', 'db.r4.large', 'db.r4.24xlarge',  48)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.large',     1) -- db.m7g
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.xlarge',    2)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.2xlarge',   4)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.4xlarge',   8)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.8xlarge',  16)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.12xlarge', 24)
        ,(TRUE, 'aurora-postgresql', 'db.m7g.large', 'db.m7g.16xlarge', 32)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.large',     1) -- db.m6g
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.xlarge',    2)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.2xlarge',   4)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.4xlarge',   8)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.8xlarge',  16)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.12xlarge', 24)
        ,(TRUE, 'aurora-postgresql', 'db.m6g.large', 'db.m6g.16xlarge', 32)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.large',    1) -- db.m6i
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.xlarge',   2)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.2xlarge',  4)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.4xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.8xlarge', 16)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.12xlarge',24)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.16xlarge',32)
        ,(FALSE, 'aurora-postgresql', 'db.m6i.large', 'db.m6i.24xlarge',48)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.large',    1) -- db.m5d
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.xlarge',   2)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.2xlarge',  4)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.4xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.8xlarge', 16)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.12xlarge',24)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.16xlarge',32)
        ,(FALSE, 'aurora-postgresql', 'db.m5d.large', 'db.m5d.24xlarge',48)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.large',      1) -- db.m5
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.xlarge',     2)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.2xlarge',    4)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.4xlarge',    8)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.8xlarge',   16)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.12xlarge',  24)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.16xlarge',  32)
        ,(FALSE, 'aurora-postgresql', 'db.m5.large', 'db.m5.24xlarge',  48)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.large',      1) -- db.m4
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.xlarge',     2)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.2xlarge',    4)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.4xlarge',    8)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.8xlarge',   16)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.12xlarge',  24)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.16xlarge',  32)
        ,(FALSE, 'aurora-postgresql', 'db.m4.large', 'db.m4.24xlarge',  48)
        ,(TRUE, 'aurora-postgresql', 'db.t4g.medium', 'db.t4g.medium',   1) -- db.t4g
        ,(TRUE, 'aurora-postgresql', 'db.t4g.medium', 'db.t4g.large',    2)
        ,(TRUE, 'aurora-postgresql', 'db.t4g.medium', 'db.t4g.xlarge',   4)
        ,(TRUE, 'aurora-postgresql', 'db.t4g.medium', 'db.t4g.2xlarge',  8)
        ,(FALSE, 'aurora-postgresql', 'db.t3.medium', 'db.t3.medium',    1) -- db.t3
        ,(FALSE, 'aurora-postgresql', 'db.t3.medium', 'db.t3.large',     2)
        ,(FALSE, 'aurora-postgresql', 'db.t3.medium', 'db.t3.xlarge',    4)
        ,(FALSE, 'aurora-postgresql', 'db.t3.medium', 'db.t3.2xlarge',   8)

         -- Aurora MySQL
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.large',     1) -- db.r7g
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.xlarge',    2)
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.2xlarge',   4)
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.4xlarge',   8)
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.8xlarge',  16)
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.12xlarge', 24)
        ,(TRUE, 'aurora-mysql', 'db.r7g.large', 'db.r7g.16xlarge', 32)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.large',     1) -- db.r6g
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.xlarge',    2)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.2xlarge',   4)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.4xlarge',   8)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.8xlarge',  16)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.12xlarge', 24)
        ,(TRUE, 'aurora-mysql', 'db.r6g.large', 'db.r6g.16xlarge', 32)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.large',    1) -- db.r6i
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.xlarge',   2)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.2xlarge',  4)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.4xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.8xlarge', 16)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.12xlarge',24)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.16xlarge',32)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.24xlarge',48)
        ,(FALSE, 'aurora-mysql', 'db.r6i.large', 'db.r6i.32xlarge',64)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.large',    1) -- db.r5b
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.xlarge',   2)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.2xlarge',  4)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.4xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.8xlarge', 16)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.12xlarge',24)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.16xlarge',32)
        ,(FALSE, 'aurora-mysql', 'db.r5b.large', 'db.r5b.24xlarge',48)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.large',    1) -- db.r5d
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.xlarge',   2)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.2xlarge',  4)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.4xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.8xlarge', 16)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.12xlarge',24)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.16xlarge',32)
        ,(FALSE, 'aurora-mysql', 'db.r5d.large', 'db.r5d.24xlarge',48)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.large',      1) -- db.r5
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.xlarge',     2)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.2xlarge',    4)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.4xlarge',    8)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.8xlarge',   16)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.12xlarge',  24)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.16xlarge',  32)
        ,(FALSE, 'aurora-mysql', 'db.r5.large', 'db.r5.24xlarge',  48)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.large',      1) -- db.r4
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.xlarge',     2)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.2xlarge',    4)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.4xlarge',    8)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.8xlarge',   16)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.12xlarge',  24)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.16xlarge',  32)
        ,(FALSE, 'aurora-mysql', 'db.r4.large', 'db.r4.24xlarge',  48)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.large',     1) -- db.m7g
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.xlarge',    2)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.2xlarge',   4)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.4xlarge',   8)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.8xlarge',  16)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.12xlarge', 24)
        ,(TRUE, 'aurora-mysql', 'db.m7g.large', 'db.m7g.16xlarge', 32)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.large',     1) -- db.m6g
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.xlarge',    2)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.2xlarge',   4)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.4xlarge',   8)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.8xlarge',  16)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.12xlarge', 24)
        ,(TRUE, 'aurora-mysql', 'db.m6g.large', 'db.m6g.16xlarge', 32)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.large',    1) -- db.m6i
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.xlarge',   2)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.2xlarge',  4)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.4xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.8xlarge', 16)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.12xlarge',24)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.16xlarge',32)
        ,(FALSE, 'aurora-mysql', 'db.m6i.large', 'db.m6i.24xlarge',48)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.large',    1) -- db.m5d
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.xlarge',   2)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.2xlarge',  4)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.4xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.8xlarge', 16)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.12xlarge',24)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.16xlarge',32)
        ,(FALSE, 'aurora-mysql', 'db.m5d.large', 'db.m5d.24xlarge',48)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.large',      1) -- db.m5
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.xlarge',     2)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.2xlarge',    4)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.4xlarge',    8)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.8xlarge',   16)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.12xlarge',  24)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.16xlarge',  32)
        ,(FALSE, 'aurora-mysql', 'db.m5.large', 'db.m5.24xlarge',  48)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.large',      1) -- db.m4
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.xlarge',     2)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.2xlarge',    4)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.4xlarge',    8)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.8xlarge',   16)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.12xlarge',  24)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.16xlarge',  32)
        ,(FALSE, 'aurora-mysql', 'db.m4.large', 'db.m4.24xlarge',  48)
        ,(TRUE, 'aurora-mysql', 'db.t4g.medium', 'db.t4g.medium',   1) -- db.t4g
        ,(TRUE, 'aurora-mysql', 'db.t4g.medium', 'db.t4g.large',    2)
        ,(TRUE, 'aurora-mysql', 'db.t4g.medium', 'db.t4g.xlarge',   4)
        ,(TRUE, 'aurora-mysql', 'db.t4g.medium', 'db.t4g.2xlarge',  8)
        ,(FALSE, 'aurora-mysql', 'db.t3.medium', 'db.t3.medium',    1) -- db.t3
        ,(FALSE, 'aurora-mysql', 'db.t3.medium', 'db.t3.large',     2)
        ,(FALSE, 'aurora-mysql', 'db.t3.medium', 'db.t3.xlarge',    4)
        ,(FALSE, 'aurora-mysql', 'db.t3.medium', 'db.t3.2xlarge',   8)

        -- PostgreSQL RDS
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.large',    1) -- db.r7g
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.r7g.large', 'db.r7g.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.large',    1) -- db.r6g
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.r6g.large', 'db.r6g.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.large',    1) -- db.r6i
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.24xlarge',48)
        ,(FALSE, 'postgresql', 'db.r6i.large', 'db.r6i.32xlarge',64)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.large',    1) -- db.r5b
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.r5b.large', 'db.r5b.24xlarge',48)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.large',    1) -- db.r5d
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.r5d.large', 'db.r5d.24xlarge',48)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.large',      1) -- db.r5
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.xlarge',     2)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.2xlarge',    4)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.4xlarge',    8)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.8xlarge',   16)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.12xlarge',  24)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.16xlarge',  32)
        ,(FALSE, 'postgresql', 'db.r5.large', 'db.r5.24xlarge',  48)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.large',      1) -- db.r4
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.xlarge',     2)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.2xlarge',    4)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.4xlarge',    8)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.8xlarge',   16)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.12xlarge',  24)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.16xlarge',  32)
        ,(FALSE, 'postgresql', 'db.r4.large', 'db.r4.24xlarge',  48)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.large',    1) -- db.m7g
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.m7g.large', 'db.m7g.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.large',    1) -- db.m6g
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.m6g.large', 'db.m6g.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.large',    1) -- db.m6i
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.m6i.large', 'db.m6i.24xlarge',48)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.large',    1) -- db.m5d
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.xlarge',   2)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.2xlarge',  4)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.4xlarge',  8)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.8xlarge', 16)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.12xlarge',24)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.16xlarge',32)
        ,(FALSE, 'postgresql', 'db.m5d.large', 'db.m5d.24xlarge',48)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.large',      1) -- db.m5
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.xlarge',     2)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.2xlarge',    4)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.4xlarge',    8)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.8xlarge',   16)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.12xlarge',  24)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.16xlarge',  32)
        ,(FALSE, 'postgresql', 'db.m5.large', 'db.m5.24xlarge',  48)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.large',      1) -- db.m4
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.xlarge',     2)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.2xlarge',    4)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.4xlarge',    8)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.8xlarge',   16)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.12xlarge',  24)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.16xlarge',  32)
        ,(FALSE, 'postgresql', 'db.m4.large', 'db.m4.24xlarge',  48)
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.micro',    1) -- db.t4g
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.small',    2)
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.medium',   4)
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.large',    8)
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.xlarge',  16)
        ,(FALSE, 'postgresql', 'db.t4g.micro', 'db.t4g.2xlarge', 32)
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.micro',      1) -- db.t3
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.small',      2)
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.medium',     4)
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.large',      8)
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.xlarge',    16)
        ,(FALSE, 'postgresql', 'db.t3.micro', 'db.t3.2xlarge',   32)

        -- MySQL RDS
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.large',    1) -- db.r7g
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.xlarge',   2)
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.12xlarge',24)
        ,(FALSE, 'mysql', 'db.r7g.large', 'db.r7g.16xlarge',32)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.large',    1) -- db.r6g
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.xlarge',   2)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.12xlarge',24)
        ,(FALSE, 'mysql', 'db.r6g.large', 'db.r6g.16xlarge',32)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.large',    1) -- db.r6i
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.xlarge',   2)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.12xlarge',24)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.16xlarge',32)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.24xlarge',48)
        ,(FALSE, 'mysql', 'db.r6i.large', 'db.r6i.32xlarge',64)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.large',    1) -- db.r5b
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.xlarge',   2)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.12xlarge',24)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.16xlarge',32)
        ,(FALSE, 'mysql', 'db.r5b.large', 'db.r5b.24xlarge',48)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.large',    1) -- db.r5d
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.xlarge',   2)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.12xlarge',24)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.16xlarge',32)
        ,(FALSE, 'mysql', 'db.r5d.large', 'db.r5d.24xlarge',48)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.large',      1) -- db.r5
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.xlarge',     2)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.2xlarge',    4)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.4xlarge',    8)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.8xlarge',   16)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.12xlarge',  24)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.16xlarge',  32)
        ,(FALSE, 'mysql', 'db.r5.large', 'db.r5.24xlarge',  48)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.large',      1) -- db.r4
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.xlarge',     2)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.2xlarge',    4)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.4xlarge',    8)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.8xlarge',   16)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.12xlarge',  24)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.16xlarge',  32)
        ,(FALSE, 'mysql', 'db.r4.large', 'db.r4.24xlarge',  48)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.large',    1) -- db.m7g
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.xlarge',   2)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.12xlarge',24)
        ,(FALSE, 'mysql', 'db.m7g.large', 'db.m7g.16xlarge',32)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.large',    1) -- db.m6g
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.xlarge',   2)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.12xlarge',24)
        ,(FALSE, 'mysql', 'db.m6g.large', 'db.m6g.16xlarge',32)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.large',    1) -- db.m6i
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.xlarge',   2)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.12xlarge',24)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.16xlarge',32)
        ,(FALSE, 'mysql', 'db.m6i.large', 'db.m6i.24xlarge',48)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.large',    1) -- db.m5d
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.xlarge',   2)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.2xlarge',  4)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.4xlarge',  8)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.8xlarge', 16)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.12xlarge',24)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.16xlarge',32)
        ,(FALSE, 'mysql', 'db.m5d.large', 'db.m5d.24xlarge',48)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.large',      1) -- db.m5
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.xlarge',     2)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.2xlarge',    4)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.4xlarge',    8)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.8xlarge',   16)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.12xlarge',  24)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.16xlarge',  32)
        ,(FALSE, 'mysql', 'db.m5.large', 'db.m5.24xlarge',  48)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.large',      1) -- db.m4
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.xlarge',     2)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.2xlarge',    4)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.4xlarge',    8)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.8xlarge',   16)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.12xlarge',  24)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.16xlarge',  32)
        ,(FALSE, 'mysql', 'db.m4.large', 'db.m4.24xlarge',  48)
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.micro',    1) -- db.t4g
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.small',    2)
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.medium',   4)
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.large',    8)
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.xlarge',  16)
        ,(FALSE, 'mysql', 'db.t4g.micro', 'db.t4g.2xlarge',  32)
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.micro',      1) -- db.t3
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.small',      2)
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.medium',     4)
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.large',      8)
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.xlarge',    16)
        ,(FALSE, 'mysql', 'db.t3.micro', 'db.t3.2xlarge',   32)

        -- Oracle
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.large',     1) -- db.r7g
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.xlarge',    2)
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.2xlarge',   4)
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.4xlarge',   8)
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.8xlarge',  16)
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.12xlarge', 24)
        ,(TRUE, 'oracle', 'db.r7g.large', 'db.r7g.16xlarge', 32)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.large',     1) -- db.r6g
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.xlarge',    2)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.2xlarge',   4)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.4xlarge',   8)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.8xlarge',  16)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.12xlarge', 24)
        ,(TRUE, 'oracle', 'db.r6g.large', 'db.r6g.16xlarge', 32)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.large',    1) -- db.r6i
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.xlarge',   2)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.2xlarge',  4)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.4xlarge',  8)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.8xlarge', 16)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.12xlarge',24)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.16xlarge',32)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.24xlarge',48)
        ,(FALSE, 'oracle', 'db.r6i.large', 'db.r6i.32xlarge',64)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.large',    1) -- db.r5b
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.xlarge',   2)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.2xlarge',  4)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.4xlarge',  8)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.8xlarge', 16)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.12xlarge',24)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.16xlarge',32)
        ,(FALSE, 'oracle', 'db.r5b.large', 'db.r5b.24xlarge',48)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.large',    1) -- db.r5d
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.xlarge',   2)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.2xlarge',  4)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.4xlarge',  8)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.8xlarge', 16)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.12xlarge',24)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.16xlarge',32)
        ,(FALSE, 'oracle', 'db.r5d.large', 'db.r5d.24xlarge',48)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.large',      1) -- db.r5
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.xlarge',     2)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.2xlarge',    4)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.4xlarge',    8)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.8xlarge',   16)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.12xlarge',  24)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.16xlarge',  32)
        ,(FALSE, 'oracle', 'db.r5.large', 'db.r5.24xlarge',  48)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.large',      1) -- db.r4
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.xlarge',     2)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.2xlarge',    4)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.4xlarge',    8)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.8xlarge',   16)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.12xlarge',  24)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.16xlarge',  32)
        ,(FALSE, 'oracle', 'db.r4.large', 'db.r4.24xlarge',  48)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.large',     1) -- db.m7g
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.xlarge',    2)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.2xlarge',   4)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.4xlarge',   8)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.8xlarge',  16)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.12xlarge', 24)
        ,(TRUE, 'oracle', 'db.m7g.large', 'db.m7g.16xlarge', 32)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.large',     1) -- db.m6g
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.xlarge',    2)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.2xlarge',   4)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.4xlarge',   8)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.8xlarge',  16)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.12xlarge', 24)
        ,(TRUE, 'oracle', 'db.m6g.large', 'db.m6g.16xlarge', 32)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.large',    1) -- db.m6i
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.xlarge',   2)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.2xlarge',  4)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.4xlarge',  8)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.8xlarge', 16)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.12xlarge',24)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.16xlarge',32)
        ,(FALSE, 'oracle', 'db.m6i.large', 'db.m6i.24xlarge',48)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.large',    1) -- db.m5d
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.xlarge',   2)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.2xlarge',  4)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.4xlarge',  8)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.8xlarge', 16)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.12xlarge',24)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.16xlarge',32)
        ,(FALSE, 'oracle', 'db.m5d.large', 'db.m5d.24xlarge',48)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.large',      1) -- db.m5
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.xlarge',     2)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.2xlarge',    4)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.4xlarge',    8)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.8xlarge',   16)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.12xlarge',  24)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.16xlarge',  32)
        ,(FALSE, 'oracle', 'db.m5.large', 'db.m5.24xlarge',  48)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.large',      1) -- db.m4
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.xlarge',     2)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.2xlarge',    4)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.4xlarge',    8)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.8xlarge',   16)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.12xlarge',  24)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.16xlarge',  32)
        ,(FALSE, 'oracle', 'db.m4.large', 'db.m4.24xlarge',  48)
        ,(TRUE, 'oracle', 'db.t4g.small', 'db.t4g.small',     1) -- db.t4g
        ,(TRUE, 'oracle', 'db.t4g.small', 'db.t4g.medium',    2)
        ,(TRUE, 'oracle', 'db.t4g.small', 'db.t4g.large',     4)
        ,(TRUE, 'oracle', 'db.t4g.small', 'db.t4g.xlarge',    8)
        ,(TRUE, 'oracle', 'db.t4g.small', 'db.t4g.2xlarge',  16)
        ,(FALSE, 'oracle', 'db.t3.small', 'db.t3.small',      1) -- db.t3
        ,(FALSE, 'oracle', 'db.t3.small', 'db.t3.medium',     2)
        ,(FALSE, 'oracle', 'db.t3.small', 'db.t3.large',      4)
        ,(FALSE, 'oracle', 'db.t3.small', 'db.t3.xlarge',     8)
        ,(FALSE, 'oracle', 'db.t3.small', 'db.t3.2xlarge',   16)
)

SELECT eligible_commit, engine, instance_commited, instance_size, multiply FROM x
